services:
  - type: web
    name: evotracker-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: evoTracker
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
